# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI/CD with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test


      - name: Docker build and push to docker hub
        run: |
          docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_PASSWORD }} 
          docker build -t webmessenger . 
          docker tag webmessenger ${{ secrets.DOCKER_ID }}/webmessenger:${GITHUB_SHA::7} 
          docker push ${{ secrets.DOCKER_ID }}/webmessenger:${GITHUB_SHA::7}

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        env: 
            GITHUB-SHA: ${GITHUB_SHA::7}
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PEM }}
          script: |
            docker pull ${{ secrets.DOCKER_ID }}/webmessenger:${{env.GITHUB-SHA}}
            docker tag ${{ secrets.DOCKER_ID }}/webmessenger:${{env.GITHUB-SHA}} webmessenger
            docker stop webmessenger || true
            docker run -d --rm --name webmessenger --network kpp -e SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/chat?useSSL=false webmessenger
