# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI/CD with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
      - name: Docker build and push to docker hub
        run: |
          echo in docker ${GITHUB_SHA::7} 

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PEM }}
          envs: GITHUB_SHA
          script: |
            echo 1 $GITHUB_SHA::7
            echo 1 ${GITHUB_SHA::7}
            docker pull ${{ secrets.DOCKER_ID }}/webmessenger:$GITHUB_SHA::7
            docker tag ${{ secrets.DOCKER_ID }}/webmessenger:$GITHUB_SHA::7 webmessenger
            docker stop webmessenger || true
            docker run -d --rm --name webmessenger --network kpp -e SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/chat?useSSL=false webmessenger
